Add nix flake to make installation easier
webosbrew/native-toolchain pull request #2
Opened 2024-05-17 00:39 UTC by Rucadi

This allows to install the toolchain in all supported architectures using Nix.

With the command: 

`nix develop github:rucadi/native-toolchain`

You will spawn a shell with the toolchain installed, all dependencies and the cmake command aliased to include the toolchain file.

I have only tested this on x86_64 linux, a compilation of SDL2 using this toolchain was successful.

2024-05-17 00:45 UTC, kitsuned requested changes

2024-05-17 00:45 UTC, kitsuned commented on flake.nix
> +          hashToolchain = {
this will break as soon as someone creates a new release.
you can pin release version in the links (e.g. `latest` → commit hash).

cc @Informatic

2024-05-17 12:54 UTC, Rucadi commented on flake.nix
> +          hashToolchain = {
Fixed! Thanks for noticing!

2024-05-18 07:13 UTC, mariotaku requested changes

2024-05-18 07:13 UTC, mariotaku commented on flake.nix
> +  description = "Cmake with webOs toolchain";
Sorry for nitpicking, but would you mind changing the cases to CMake and webOS?

2024-05-18 07:46 UTC, Rucadi commented on flake.nix
> +  description = "Cmake with webOs toolchain";
I changed it among other changes, between them, I added a command to initialize the vscode cmake kit and added glib-2.0 includes (for some reason these were failing in some projects I tried to build and had to manually add them)

2024-05-18 11:33 UTC, mariotaku commented on flake.nix
> +  description = "Cmake with webOs toolchain";
May I have the sample code to reproduce the build issue? I probably can fix that if it's caused by the toolchain

2024-05-18 12:47 UTC, Rucadi commented on flake.nix
> +  description = "Cmake with webOs toolchain";
Sure, I'm able to reproduce it in your own projects, here I have a Dockerfile that will help you reproduce it:

```
FROM ubuntu

RUN apt update && apt install -y curl xz-utils sudo git
RUN useradd -ms /bin/bash broken-toolchain && echo "broken-toolchain ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
USER broken-toolchain
RUN bash -c 'sh <(curl -L https://nixos.org/nix/install) --no-daemon'

WORKDIR /home/broken-toolchain
RUN mkdir -p .config/nix && echo "experimental-features = nix-command flakes" > .config/nix/nix.conf
RUN git clone --recursive https://github.com/mariotaku/ihsplay.git
RUN mkdir -p /home/broken-toolchain/ihsplay/build
WORKDIR /home/broken-toolchain/ihsplay/build

#prefetch
RUN /home/broken-toolchain/.nix-profile/bin/nix develop github:rucadi/native-toolchain/8e9e8f81a96c99c7cff879a30ee9e0bccde1ef3b -c "/usr/bin/env"
CMD /home/broken-toolchain/.nix-profile/bin/nix develop github:rucadi/native-toolchain/8e9e8f81a96c99c7cff879a30ee9e0bccde1ef3b 
```

![image](https://github.com/webosbrew/native-toolchain/assets/6445619/75287468-5726-4318-9394-c8a2e26861f7)

To replicate:
```
docker build . -t broken
docker run -it --rm broken
cmake ..
make -j8
```

notice that I'm using the commit 8e9e8f81a96c99c7cff879a30ee9e0bccde1ef3b , which is the one unpatched.

2024-05-18 13:56 UTC, mariotaku commented on flake.nix
> +  description = "Cmake with webOs toolchain";
Hmm, maybe I made some mistakes in `ss4s` codebase. Can you update the submodule ss4s to `944470d2` and try again?

2024-05-18 14:02 UTC, Rucadi commented on flake.nix
> +  description = "Cmake with webOs toolchain";
![image](https://github.com/webosbrew/native-toolchain/assets/6445619/24765be4-341a-47d9-88b9-48450847bb6f)
It still gives an error with that commit

2024-05-18 14:09 UTC, mariotaku commented on flake.nix
> +  description = "Cmake with webOs toolchain";
Is the build cache invalidated? Doesn't look right. Or you can just delete lines from `ss4s_add_module(smp-webos3 FOR_AUDIO FOR_VIDEO`.

2024-05-18 14:14 UTC, Rucadi commented on flake.nix
> +  description = "Cmake with webOs toolchain";
> Is the build cache invalidated? Doesn't look right. Or you can just delete lines from `ss4s_add_module(smp-webos3 FOR_AUDIO FOR_VIDEO`.

From a clean docker container  this is my history
```
   1  cd ..
    3  cd third_party/
    7  cd ss4s/
    9  git checkout 944470d2 
   10  git fetch && git checkout 944470d2 
   11  cd ..
   13  mkdir build
   14  cd build/
   16  cmake ..
   17  make -j20
```
It still leads to failure.

2024-05-18 14:17 UTC, Rucadi commented on flake.nix
> +  description = "Cmake with webOs toolchain";
Regardless of that, If you are confident that this is an specific-project problem, then I should remove that line from the cmake alias

2024-05-18 15:25 UTC, mariotaku commented on flake.nix
> +  description = "Cmake with webOs toolchain";
Yeah, I think that line should be removed. Nevertheless if I could reproduce the issue, I'll fix in the upstream :)

2024-05-18 16:15 UTC, Rucadi commented on flake.nix
> +  description = "Cmake with webOs toolchain";
Done!

2024-05-19 01:49 UTC, mariotaku approved these changes

2024-05-19 01:49 UTC, merged